# Generated by Django 5.2.6 on 2025-09-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_module', '0004_individualwallet_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualwalletotprequest',
            name='cache_key',
            field=models.CharField(blank=True, help_text='Cache key for OTP validation', max_length=255, null=True),
        ),
    ]
