# Generated by Django 6.0.2 on 2026-02-27 21:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_module', '0006_individualexpense_individualsavingswallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('GOLD', 'Gold Plan'), ('INSURANCE', 'Insurance'), ('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit'), ('MUTUAL_FUND', 'Mutual Funds'), ('STOCK', 'Stock Market')], max_length=20)),
                ('description', models.TextField()),
                ('benefits', models.TextField(help_text='Key benefits of this plan')),
                ('risk_level', models.CharField(default='Low to Medium', max_length=50)),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('current_scenario_analysis', models.TextField(help_text='Current market scenario analysis for this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='individualwallet',
            name='total_deposits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
