# Generated by Django 6.0.2 on 2026-03-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_module', '0007_investmentsuggestion_individualwallet_total_deposits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentsuggestion',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='investmentsuggestion',
            name='current_scenario_analysis',
            field=models.TextField(),
        ),
    ]
