# Generated by Django 5.2.5 on 2025-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplealert',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='couplealert',
            name='message_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='couplealert',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='couplealert',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharedtransaction',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sharedtransaction',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spendingrequest',
            name='category_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spendingrequest',
            name='category_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spendingrequest',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spendingrequest',
            name='description_ta',
            field=models.TextField(null=True),
        ),
    ]
