# Generated by Django 5.2.5 on 2025-09-21 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_module', '0002_couplealert_message_en_couplealert_message_ta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('joint_goals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_locked', models.BooleanField(default=False, help_text='Lock wallet for security reasons')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_wallet_partner1', to=settings.AUTH_USER_MODEL)),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_wallet_partner2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('partner1', 'partner2')},
            },
        ),
        migrations.CreateModel(
            name='CoupleWalletOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(help_text='Type of operation requiring OTP', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_otp_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to='couple_module.couplewallet')),
            ],
        ),
        migrations.CreateModel(
            name='CoupleWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('EMERGENCY_TRANSFER', 'Emergency Fund Transfer'), ('GOAL_TRANSFER', 'Joint Goal Transfer'), ('BUDGET_ALLOCATION', 'Budget Allocation'), ('EXPENSE_SPLIT', 'Expense Split')], max_length=20)),
                ('description', models.TextField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emergency_fund_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joint_goals_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='couple_module.couplewallet')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
