# Generated by Django 6.0.2 on 2026-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_module', '0005_couplepersonalwallet_jointgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplewallettransaction',
            name='category',
            field=models.CharField(default='OTHER', help_text='Expense category (Rent, Groceries, etc.)', max_length=50),
        ),
    ]
