# Generated by Django 5.2.5 on 2025-09-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywage_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of the work or source', null=True),
        ),
        migrations.AddField(
            model_name='dailysalary',
            name='description_ta',
            field=models.TextField(blank=True, help_text='Description of the work or source', null=True),
        ),
        migrations.AddField(
            model_name='expensetracking',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensetracking',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100, verbose_name='Name')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', verbose_name='Bio')),
                ('location', models.CharField(blank=True, help_text='Where are you based?', max_length=100, verbose_name='Location')),
                ('birth_date', models.DateField(blank=True, help_text='When is your birthday?', null=True, verbose_name='Birth Date')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
