# Generated by Django 5.2.5 on 2025-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_module', '0002_parentotprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentalert',
            name='alert_type_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentalert',
            name='alert_type_ta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentalert',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentalert',
            name='message_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentotprequest',
            name='reason_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parentotprequest',
            name='reason_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmonitoring',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmonitoring',
            name='notes_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
