# Generated by Django 5.2.5 on 2025-09-24 11:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiree_module', '0004_alter_retireetransaction_transaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetireeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pension_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dedicated pension funds', max_digits=10)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Emergency fund balance', max_digits=10)),
                ('monthly_expense_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_locked', models.BooleanField(default=False, help_text='Lock wallet for security reasons')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetireeWalletOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(help_text='Type of operation requiring OTP', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetireeWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('PENSION_DEPOSIT', 'Pension Deposit'), ('EMERGENCY_DEPOSIT', 'Emergency Fund Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('FORECAST_EXPENSE', 'Forecast Expense')], max_length=20)),
                ('description', models.TextField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pension_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='retiree_module.retireewallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
