# Generated by Django 5.2.5 on 2025-09-01 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_chatmessage_dailylimit_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylimit',
            name='current_daily_spent',
        ),
        migrations.RemoveField(
            model_name='dailylimit',
            name='daily_limit_amount',
        ),
        migrations.RemoveField(
            model_name='dailylimit',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='dailylimit',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_type',
        ),
        migrations.AddField(
            model_name='dailylimit',
            name='current_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailylimit',
            name='daily_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailylimit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='alert_percentage',
            field=models.IntegerField(choices=[(50, '50%'), (70, '70%'), (100, '100%')], default=50),
        ),
        migrations.AddField(
            model_name='reminder',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.budget'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailylimit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_otp_responses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
