# Generated by Django 5.2.5 on 2025-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0003_remove_dailylimit_current_daily_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Enter your name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ta',
            field=models.CharField(help_text='Enter your name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_ta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=100, verbose_name='Name'),
        ),
    ]
