# Generated by Django 5.2.6 on 2025-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0005_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_transaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
