# Generated by Django 6.0.2 on 2026-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0006_wallet_last_transaction_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
