# Generated by Django 6.0.2 on 2026-02-21 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0007_wallet_failed_attempts_wallet_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWalletOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(help_text='Type of operation requiring OTP', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('cache_key', models.CharField(blank=True, help_text='Cache key for OTP validation', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_wallet_otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
