# Generated by Django 6.0.2 on 2026-02-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0011_allowancecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='special_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
