# Generated by Django 6.0.2 on 2026-03-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0013_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('INDIVIDUAL', 'Individual'), ('COUPLE', 'Couple'), ('RETIREE', 'Retiree'), ('DAILY_WAGE', 'Daily Wage'), ('INSTITUTE_OWNER', 'Institute Owner'), ('INSTITUTE_TEACHER', 'Institute Teacher')], max_length=20, null=True),
        ),
    ]
