# Generated by Django 6.0.2 on 2026-03-02 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0014_alter_user_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativespendingtracker',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_spending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('INDIVIDUAL', 'Individual'), ('COUPLE', 'Couple'), ('INSTITUTE_OWNER', 'Institute Owner'), ('INSTITUTE_TEACHER', 'Institute Teacher')], max_length=20, null=True),
        ),
    ]
