# Generated by Django 6.0.2 on 2026-03-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0015_alter_cumulativespendingtracker_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
