# Generated by Django 6.0.2 on 2026-03-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0016_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyallowance',
            name='daily_limit_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override for daily spending limit', max_digits=10, null=True),
        ),
    ]
