# Generated by Django 6.0.2 on 2026-03-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0017_monthlyallowance_daily_limit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('STUDENT_ACADEMIC', 'Student (Academic)'), ('PARENT', 'Parent'), ('INDIVIDUAL', 'Individual'), ('COUPLE', 'Couple'), ('INSTITUTE_OWNER', 'Institute Owner'), ('INSTITUTE_TEACHER', 'Institute Teacher'), ('RETIREE', 'Retiree')], max_length=20, null=True),
        ),
    ]
