# Generated by Django 5.2.5 on 2025-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensealert',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expensealert',
            name='message_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expensealert',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensealert',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
