# Generated by Django 5.2.6 on 2025-09-28 20:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_module', '0003_individualwallet_individualwalletotprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualwallet',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Threshold for low balance alerts', max_digits=10),
        ),
    ]
