# Generated by Django 5.2.5 on 2025-09-24 11:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywage_module', '0002_dailysalary_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWageWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('daily_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('weekly_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monthly_goal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('emergency_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_locked', models.BooleanField(default=False, help_text='Lock wallet for security reasons')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dailywage_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWageWalletOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(help_text='Type of operation requiring OTP', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField()),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailywage_otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWageWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_type', models.CharField(choices=[('DAILY_EARNINGS', 'Daily Earnings'), ('WITHDRAWAL', 'Withdrawal'), ('EMERGENCY_TRANSFER', 'Emergency Reserve Transfer'), ('ESSENTIAL_EXPENSE', 'Essential Expense'), ('NON_ESSENTIAL_EXPENSE', 'Non-Essential Expense')], max_length=25)),
                ('description', models.TextField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_earnings_after', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('emergency_reserve_after', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_essential_expense', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dailywage_module.dailywagewallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
