# Generated by Django 5.2.6 on 2025-09-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywage_module', '0003_dailywagewallet_dailywagewalletotprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywagewalletotprequest',
            name='cache_key',
            field=models.CharField(default='', help_text='Cache key for OTP validation', max_length=100),
        ),
    ]
