# Generated by Django 5.2.6 on 2025-10-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywage_module', '0005_dailywagewallet_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='persona',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COUPLE', 'Couple'), ('PARENT', 'Parent'), ('STUDENT', 'Student'), ('DAILY_WAGE', 'Daily Wage Worker'), ('RETIREE', 'Retiree')], default='INDIVIDUAL', help_text='Select your account type', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=20, verbose_name='Phone'),
        ),
    ]
