# Generated by Django 5.2.6 on 2025-09-28 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_module', '0003_couplewallet_couplewalletotprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplewallet',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Threshold for low balance alerts', max_digits=10),
        ),
        migrations.AddField(
            model_name='couplewalletotprequest',
            name='cache_key',
            field=models.CharField(default='', help_text='Cache key for OTP validation', max_length=255),
        ),
    ]
