# Generated by Django 5.2.5 on 2025-09-09 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiree_module', '0002_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='message_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='category_name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='notes_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='source_type_en',
            field=models.CharField(help_text='e.g., Pension, Investment, Rental', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='source_type_ta',
            field=models.CharField(help_text='e.g., Pension, Investment, Rental', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RetireeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetireeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetireeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense')], max_length=3)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
