# Generated by Django 5.2.5 on 2025-09-14 17:07

import retiree_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiree_module', '0003_alert_message_en_alert_message_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retireetransaction',
            name='transaction_date',
            field=models.DateField(default=retiree_module.models.get_today),
        ),
    ]
