# Generated by Django 6.0.2 on 2026-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutestudentprofile',
            name='student_name',
            field=models.CharField(default='', help_text='Full name of the student', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='institutestudentprofile',
            unique_together={('institute', 'student_name', 'parent_mobile')},
        ),
    ]
