# Generated by Django 6.0.2 on 2026-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_module', '0003_alter_institutestudentprofile_enrolled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fee for the month', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10),
        ),
    ]
