# Generated by Django 6.0.2 on 2026-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_module', '0004_remove_feepayment_amount_feepayment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='institute_module.institutestudentprofile'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total fee for the month', max_digits=10),
        ),
    ]
