# Generated by Django 6.0.2 on 2026-03-09 05:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_module', '0005_teacherprofile_assigned_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='pay_day',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='base_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='extra_session_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='working_days_per_month',
            field=models.PositiveIntegerField(default=26),
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('OVERTIME', 'Overtime / Weekend')], default='PRESENT', max_length=20)),
                ('extra_sessions', models.PositiveIntegerField(default=0, help_text='Number of extra classes/hours taken')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='institute_module.teacherprofile')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
